version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: trilatrip-db

    restart: always

    environment:
      POSTGRES_USER: trilatrip
      POSTGRES_PASSWORD: trilatrip
      POSTGRES_DB: trilatrip

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: